---
# Overrides to test all of the roles and modules
#
# For use in VMs, does not work in containers

m_base: true
m_calc: true
m_sscan: true
m_busy: true
m_p4p: true
m_pvaPy: true
m_seq: true
m_opcua: true
m_stream: true
m_areadetector: true

catrust: false
epics_tools: true
oac_tree: true
archiver_appliance: true
docker: true
bluesky: true
