---
- name: Install SNCSEQ
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_seq_modules }}"
  when: not (m_seq_installed | default(false))

- name: Mark m-seq as installed
  set_fact:
    m_seq_installed: true
