---
- name: Install AreaDetector and dependencies
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_areadetector_modules }}"
  when: not (m_areadetector_installed | default(false))

- name: Mark m-areadetector as installed
  set_fact:
    m_areadetector_installed: true
