---
- name: Install P4P
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_p4p_modules }}"
  when: not (m_p4p_installed | default(false))

- name: Mark m-p4p as installed
  set_fact:
    m_p4p_installed: true
