---
- name: "{{ module.name }} | Ensure configure/os directory exists"
  ansible.builtin.file:
    path: "{{ epics_install_path }}/{{ module.id }}-{{ module.version }}/configure/os"
    state: directory
    mode: '0755'
  become: true

- name: "{{ module.name }} | Set python version"
  ansible.builtin.copy:
    dest: "{{ epics_install_path }}/{{ module.id }}-{{ module.version }}/configure/os/CONFIG_SITE.Common.linuxCommon"
    content: "PYTHON = python3\n"
  become: true
