---
- name: Install autosave
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_autosave_modules }}"
  when: not (m_autosave_installed | default(false))

- name: Mark m-autosave as installed
  set_fact:
    m_autosave_installed: true
