---
stream_version: "2.8.26"

m_stream_modules:
  - id: stream
    name: "StreamDevice"
    version: "{{ stream_version }}"
    url: "https://github.com/paulscherrerinstitute/StreamDevice/archive/refs/tags/{{ stream_version }}.tar.gz"
    release_var: "STREAM"
    release_sortkey: "10"
    pre_hook: "stream_prep.yml"
    args: -j {{ ansible_facts.processor_vcpus }}
