---
m_autosave_modules:
  - id: autosave
    name: "autoSaveRestore"
    version: "5.11"
    url: "https://github.com/epics-modules/autosave/archive/refs/tags/R5-11.tar.gz"
    release_var: "AUTOSAVE"
    release_sortkey: "10"
