---
- name: Install OPC UA
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_opcua_modules }}"
  when: not (m_opcua_installed | default(false))

- name: Mark m-opcua as installed
  set_fact:
    m_opcua_installed: true
