---
m_seq_modules:
  - id: seq
    name: "SNL Sequencer"
    version: "2.2.9"
    url: "https://github.com/epics-modules/sequencer/archive/refs/tags/R2-2-9.tar.gz"
    release_var: "SNCSEQ"
    release_sortkey: "10"
    add_to_path: true
    required_debs:
      - re2c
    required_rpms:
      - re2c
    args: -j {{ ansible_facts.processor_vcpus }}
