# Default configuration for the available roles

# minimal defaults for fast testing - copy local.yml.sample or everything.yml
# to local.yml and adjust as needed
initial_setup: false
docker: true # for rootful this needs to happen before first reboot
catrust: false
epics_tools: false
oac_tree: false
archiver_appliance: false
bluesky: false

m_base: true

# Default: false proxy
proxy_env: {}

# when building inside a container during CI this is set to true
in_container: false
