---
distro:
  gnome_group: "gnome-desktop"
  devel_group: "development-tools"
  gdm_config: "/etc/gdm/custom.conf"
  installer: "dnf"
  openssl_config: "/etc/crypto-policies/back-ends/opensslcnf.config"
  system_ca_trust_dir: "/etc/pki/ca-trust/source/anchors"
  system_ca_trust_update: "/usr/bin/update-ca-trust"
  lib_dirname: "lib64"

is_debian: false
is_redhat: true

docker: "podman"
