---
distro:
  gnome_group: "gnome-core"
  gdm_config: "/etc/gdm3/custom.conf"
  installer: "apt"
  openssl_config: "/etc/ssl/openssl.cnf"
  system_ca_trust_dir: "/usr/local/share/ca-certificates"
  system_ca_trust_update: "/usr/sbin/update-ca-certificates"
  lib_dirname: "lib"

is_debian: true
is_redhat: false

docker: "docker"
