---
m_asyn_modules:
  - id: asyn
    name: "ASYN"
    version: "4.44.2"
    url: "https://github.com/epics-modules/asyn/archive/refs/tags/R4-44-2.tar.gz"
    release_var: "ASYN"
    release_sortkey: "10"
    required_debs:
      - libtirpc-dev
    required_rpms:
      - rpcgen
      - libtirpc-devel
    enable_repos:
      - crb
    pre_hook: "{{ role_path }}/tasks/asyn_prep.yml"
    args: -j {{ ansible_facts.processor_vcpus }}
