---
- name: Install pvaPy
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_pvapy_modules }}"
  when:
    - not (m_pvapy_installed | default(false))
    - ansible_distribution == 'Rocky'

- name: Mark m-pvaPy as installed
  set_fact:
    m_pvapy_installed: true
