---
- name: Install pvaPy
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_pvapy_modules }}"
  when:
    - not (m_pvapy_installed | default(false))
    - (ansible_facts['distribution'] == 'Rocky' and ansible_facts.distribution_major_version == '8') or (ansible_facts['distribution'] == 'Ubuntu' and ansible_facts.distribution_release != 'noble')

- name: Mark m-pvaPy as installed
  set_fact:
    m_pvapy_installed: true
