---
- name: Install sscan and dependencies
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_sscan_modules }}"
  when: not (m_sscan_installed | default(false))

- name: Mark m-sscan as installed
  set_fact:
    m_sscan_installed: true
