---
- name: "{{ module.name }} pre-build hook | Fix configure/RELEASE"
  ansible.builtin.lineinfile:
    path: "{{ epics_install_path }}/{{ module.id }}-{{ module.version }}/configure/RELEASE"
    regexp: '^SNCSEQ='
    state: absent
  become: true
