---
- name: Install calc and dependencies
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_calc_modules }}"
  when: not (m_calc_installed | default(false))

- name: Mark m-calc as installed
  set_fact:
    m_calc_installed: true
