---
- name: Install StreamDevice
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_stream_modules }}"
  when: not (m_stream_installed | default(false))

- name: Mark m-stream as installed
  set_fact:
    m_stream_installed: true
