---
- name: Install ASYN
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_asyn_modules }}"
  when: not (m_asyn_installed | default(false))

- name: Mark m-asyn as installed
  set_fact:
    m_asyn_installed: true
