---
- name: Install EPICS Base and PVXS
  include_role:
    name: epics-module
  vars:
    epics_modules_to_build: "{{ m_base_modules }}"
  when: not (m_base_installed | default(false))

- name: Mark m-base as installed
  set_fact:
    m_base_installed: true
